title: "My Portfolio"
description: "Welcome to my portfolio website."
baseurl: "/portfolio" # This should be the name of your repository
url: "https://jusydun.github.io" # Your GitHub Pages URL
theme: minima # Use the Minima theme
